---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: microsoft/aspnetcore-build
    tag: "2.0.0"

inputs:
  - name: git-repo

outputs:
  - name: artifact

run:
  path: git-repo/ci/scripts/build.sh
